### ISSUE TITLE
Provide documentation in `.lua` and `.xsd` instead of `.txt`

### ISSUE THREAD

**Issue by fsmorygo** [esoui/esoui#2]
It could be very convenient to have them as source files in order to use them for code assistance in IDEs

**Comment by Baertram** [comment]
Unfortunately we will only get the txt file from ZOs.

We can parse them to build our own auto completion files, e.g:

Eclipse
https://www.esoui.com/downloads/info2068-EclipseLDTAutocomplete.html
https://cdn.esoui.com/forums/showthread.php?t=7924

IntelliJ IDEA
https://www.esoui.com/forums/showpost.php?p=41065&postcount=52
->Includes txt parse php classes by Reaby (modified by Baertram)

VS ESO addon framework
https://github.com/martin-repo/eso-addon-framework/wiki/Getting-Started

But you always need to update some files manually after each patch as not all is included into the txt files, but only in the lua code files which sirinsidiator currently uploads here, after ZOs patches appear.

ESO source file extraction tool:
https://www.esoui.com/downloads/info2532-BlackBookBrowser.html
